# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_locale', models.CharField(blank=True, max_length=255)),
                ('device_os', models.SmallIntegerField(choices=[(1, 'iOS'), (2, 'Android')])),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', related_query_name='device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'swappable': 'DJANGO_PUSH_DEVICE_MODEL',
            },
        ),
    ]
